language: rust
sudo: false

matrix:
  fast_finish: true
  include:
    - rust: nightly

    - rust: nightly
      env: RUSTFLAGS='--cfg rayon_hash_unstable'

branches:
  only:
    - master
    - staging
    - trying
